### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by matteodisabatino**
I added some options and methods that were added in mongoose-type-email but not here.

An option in particular (allowBlank) is necessary in my case.

### CODE REVIEW

**Comment by konsumer** [comment]
Looks good. thanks.

**Comment by konsumer** [comment]
Published as `1.0.7`

**Comment by konsumer** [comment]
@matteodisabatino Isn't `required` the same as `allowBlank` (inverted)? I think at one point I  patterned the options after some existing types to ensure that is basically matched the existing stuff.

**Comment by konsumer** [comment]
Here is my unit-test, which is failing. If this test isn't correct can you fix it?
https://github.com/konsumer/mongoose-type-url/blob/master/test/mongoose-type-url.test.js#L31-L38

**Comment by matteodisabatino** [comment]
@konsumer I thought so but in a project of mine it didn't work. Here my schema.

```javascript
const MySchema = new Schema({
  // other attributes
  ecommerce: {
    type: mongoose.SchemaTypes.Url
  }
  // other attributes
}, {
  minimize: false,
  timestamps: true,
  useNestedStrict: true
})

```

If a create a resource with a valid URL in ecommerce field and then I modify ecommerce putting an empty string, the model don't validate.

**Comment by matteodisabatino** [comment]
> Here is my unit-test, which is failing. If this test isn't correct can you fix it?
> https://github.com/konsumer/mongoose-type-url/blob/master/test/mongoose-type-url.test.js#L31-L38

@konsumer simply remove option `{ required: true }`. As you can see in my code the field must not be required :-)

**Comment by konsumer** [comment]
> I thought so but in a project of mine it didn't work. 
> simply remove option `{ required: true }`. 

Hmm, maybe we should work on that. I think it was originally meant to (required + value=`""` should fail.) I'd have to dig back into some other mongoose field definitions to be sure, but I think `String` does this, which this lib should approximate. It's been years since I really worked on these mongoose field-types, so they could probly both use some love.

**Comment by matteodisabatino** [comment]
If I can be helpful let me know ;-).
Anyway in the least Mongoose versions (I suppose v5.*), all works as you described if you add the option `{ minimize: false }` in the schema. And I added it. But when I follow the scenario I said, I always get a validation error.

**Comment by konsumer** [comment]
I just tested `String` with this:

```js
const UserString = mongoose.model('UserString', new mongoose.Schema({
  url: { type: String, required: true }
}))

it('should require a value for a String', function (done) {
    var user = new UserString()
    user.validate(function (err) {
      expect(err.errors.url.message).toEqual('Path `url` is required.')
      done()
    })
  })
  it('should require a value for a String', function (done) {
    var user = new UserString()
    user.url = ''
    user.validate(function (err) {
      expect(err.errors.url.message).toEqual('Path `url` is required.')
      done()
    })
  })
```

And it works, so I think maybe both libs should be bumped on minor-version, and act the same as `String` with required.

**Comment by konsumer** [comment]
In either case, I am getting this error with my test:

```js
  it('blank value should fail', function (done) {
    var user = new UserRequiredAllowBlank()
    user.validate(function (err) {
      expect(err.errors.url.message).toEqual('Path `url` is required.')
      user.url = ''
      user.validate(done)
    })
  })
```

```
ValidationError: UserRequiredAllowBlank validation failed: url: Cast to String failed for value "" at path "url"
```

**Comment by matteodisabatino** [comment]
So, if I understood, if you use type String the test passes but if you use type mongoose.SchemaTypes.Url (including option allowBlank = true) the test doesn't pass. Correct?

**Comment by konsumer** [comment]
> So, if I understood, if you use type String the test passes but if you use type mongoose.SchemaTypes.Url (including option allowBlank = true) the test doesn't pass. Correct?

Yep, I tried the `UserRequiredAllowBlank` with `allowBlank` on and off, and I get that same error.  I think my original intent (if I am remembering correctly) was that the fields basically act like `String`, but with the added validation with regex.

**Comment by matteodisabatino** [comment]
Understood. So... what can we do to have a correct validation?

**Comment by konsumer** [comment]
Maybe something like this?
```js
function validateUrl (val, options) {
  var required = (typeof options.required === 'function') ? options.required() : options.required
  if ((!val || val === '') && !required) {
    return true
  }
  return regUrl.test(val)
}
```

I will do some tests.

**Comment by konsumer** [comment]
I just pushed that with some unit-tests, including testing `String` to see how it behaves. Have a look, and if it works for your situation (maybe make a unit-test that replicates your problem), I can publish.

**Comment by matteodisabatino** [comment]
Very well and thank you :-)
But technically an empty string is not a URL. Some c.

**Comment by konsumer** [comment]
> But technically an empty string is not a URL. Some c.

We can add back an `allowBlank`, I guess. I feel like `required` means "it must be set and not be blank" where as not required means "it's ok if it's not set or is blank, but if it is set, it needs to be a valid URL".

**Comment by konsumer** [comment]
I added a new test case `invalid URL on non-required should fail`. If there are no objections, I will publish this, and I should probly make sure `mongoose-type-emaIl` works similarly.

**Comment by matteodisabatino** [comment]
@konsumer in my opinion I can proceed :-)

**Comment by konsumer** [comment]
Ok, published as `2.0.0` whcih should keep it from braking on apps that use old params.

**Pull request merged**
